### ISSUE TITLE
[MSHARED-319] Filtering throws NPE when using JDK8

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-filtering#189]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** opened **[MSHARED-319](https://issues.apache.org/jira/browse/MSHARED-319?redirect=false)** and commented

```
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.ArrayList.removeAll(ArrayList.java:674)
        at org.apache.maven.shared.filtering.DefaultMavenFileFilter.getDefaultFi
lterWrappers(DefaultMavenFileFilter.java:217)
        at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(Def
aultMavenFileFilter.java:76)
```

This happens when the following situation occurs:

```
// request.getFileFilters()  is null
buildFilters.removeAll( request.getFileFilters() );
```

Root cause: https://bugs.openjdk.java.net/browse/JDK-8015656
So let's do the null check in the maven-filtering codebase.

---

**Affects:** maven-filtering-1.1

**Issue Links:**
- [MNG-5551](https://issues.apache.org/jira/browse/MNG-5551) check that everything compile and run fine with Java 8

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [r1563467](http://svn.apache.org/r1563467)
