### ISSUE TITLE
[MSHARED-325] maven-filtering 1.2 throws MavenFilteringException: Mark invalid

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-filtering#195]
**[Mikolaj Izdebski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mizdebsk)** opened **[MSHARED-325](https://issues.apache.org/jira/browse/MSHARED-325?redirect=false)** and commented

maven-filtering 1.2 throws MavenFilteringException: Mark invalid on some resource files, which filtering is successfull with version 1.1.

An example payload is attached.  I will attach a reproducer as a unit test too.

```
Caused by: org.apache.maven.shared.filtering.MavenFilteringException: Mark invalid
	at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:129)
	at org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering.filterResources(DefaultMavenResourcesFiltering.java:264)
	at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:301)
	... 21 more
Caused by: java.io.IOException: Mark invalid
	at java.io.BufferedReader.reset(BufferedReader.java:505)
	at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:416)
	at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:205)
	at java.io.Reader.read(Reader.java:140)
	at org.apache.maven.shared.utils.io.IOUtil.copy(IOUtil.java:181)
	at org.apache.maven.shared.utils.io.IOUtil.copy(IOUtil.java:168)
	at org.apache.maven.shared.utils.io.FileUtils.copyFile(FileUtils.java:1856)
	at org.apache.maven.shared.utils.io.FileUtils.copyFile(FileUtils.java:1804)
	at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:114)
	... 23 more
```

---

**Affects:** maven-filtering-1.2

**Attachments:**
- [0001-Add-unit-test-for-MSHARED-325.patch](https://issues.apache.org/jira/secure/attachment/12719046/0001-Add-unit-test-for-MSHARED-325.patch) (_3.93 kB_)
- [MSHARED-325-tests.patch](https://issues.apache.org/jira/secure/attachment/12719045/MSHARED-325-tests.patch) (_3.69 kB_)
- [payload](https://issues.apache.org/jira/secure/attachment/12719096/payload) (_29 bytes_)

**Issue Links:**
- [MWAR-331](https://issues.apache.org/jira/browse/MWAR-331) IOException: Mark invalid -- With version 2.5
 (_**"is depended upon by"**_)
- [MRESOURCES-192](https://issues.apache.org/jira/browse/MRESOURCES-192) Upgrade maven-filtering to 1.3
 (_**"is depended upon by"**_)

1 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Mikolaj Izdebski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mizdebsk)** commented

Reproducer in a form of unit test

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Found the cause: the Reader has collected more characters then the readAheadLimit of 22 (calculated default). Increasing this value is the easy solution until someone else hits the new limit. This used to work before the fix of MSHARED-199.
For now, just escape such characters.

**Comment by jira-importer** [comment]
**[Anthony Whitford](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=awhitford)** commented

Escaping doesn't solve my problem because I need to filter a build derivative of which I have limited control over its composition...  As a result, it would be great to see this issue part of the Road Map.  :)

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Testcase applied in r1632144, thanks for some great tests !

Fixed in r1632145

**Comment by jira-importer** [comment]
**[Anthony Whitford](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=awhitford)** commented

I took the liberty of testing this updated `maven-filtering` artifact and it seems to have solved my build problem.  Thank you for fixing this.
