### ISSUE TITLE
[MSHARED-514] if filter file does not exist it should optionally ignore it, not just throw an exception

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-filtering#212]
**[richard stevenson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rstevenson)** opened **[MSHARED-514](https://issues.apache.org/jira/browse/MSHARED-514?redirect=false)** and commented

If you have a list of filter files

\<filters>
\<filter>a.properties\</filter>
\<filter>b.properties\</filter>
\<filter>${prop.name}.properties\</filter>
\</filters>

It would be nice to tell the resources plugin to optioanlly ignore a file if it does not exist. Currently get the following stack trace:

org.apache.maven.lifecycle.LifecycleExecutionException: Error loading property f
ile 'D:\projects\.../src/main/filters/a.filter.properties'
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:6
0)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.plugin.MojoExecutionException: Error loading propert
y file 'D:\projects\.../src/main/filters/a.filter.properties'
at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo
.java:269)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:694)
... 17 more
Caused by: org.apache.maven.shared.filtering.MavenFilteringException: Error load
ing property file 'D:\projects\.../src/main/filters/a.properties'
at org.apache.maven.shared.filtering.DefaultMavenFileFilter.loadProperti
es(DefaultMavenFileFilter.java:274)
at org.apache.maven.shared.filtering.DefaultMavenFileFilter.getDefaultFi
lterWrappers(DefaultMavenFileFilter.java:199)
at org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering.filt
erResources(DefaultMavenResourcesFiltering.java:162)
at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo
.java:265)
... 19 more
Caused by: java.io.FileNotFoundException: D:\projects\.../src/main/filters/a.fil
ter.properties
at org.apache.maven.shared.filtering.PropertyUtils.loadPropertyFile(Prop
ertyUtils.java:65)
at org.apache.maven.shared.filtering.DefaultMavenFileFilter.loadProperti
es(DefaultMavenFileFilter.java:269)
... 22 more

---

**Affects:** maven-filtering-3.1.0

**Attachments:**
- [maven-filter.patch](https://issues.apache.org/jira/secure/attachment/12718408/maven-filter.patch) (_1.86 kB_)

5 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Dmitry Katsubo](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dma_k)** commented

Suresh, maven-filtering v1.0 that you refer dates to 2011. Does it include the patch (created in Jan 2012)?
Also it would be nice to have an option to disable exception at all (just print warnings), as in my case I have one property file which I would like to ignore...

**Comment by jira-importer** [comment]
**[Deepak Panchal](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=deepan)** commented

I also want to have such a feature. The use case in my case is I want the developers to optionally specify their local settings that will override the default which is either specified as default proeprties in the pom file itself or within another filter proeprties file.
Having an option to ignore missing makes this possible.

**Comment by jira-importer** [comment]
**[Kerstin Klein](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=frau-klein)** commented

I just ran into this, similar scenario as in previous comment: there are general and specific properties file which may exist to overwrite a certain configuration. Only workaround I see is to create a plethora of dummy property files to allow filtering at the level we need. Is there any update on if and when this issue may get addressed?
